name: Lint Python

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Flake8
        run: pip install flake8 flake8-import-order
      - name: Linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
